### 3.1 Rounding Numerical Values

In [1]:
round(1.23, 1)

1.2

In [2]:
round(1.27, 1)

1.3

In [3]:
round(-1.27, 1)

-1.3

In [4]:
a = 2.1
b = 4.2
c = a+b
c

6.300000000000001

In [5]:
c = round(c, 2)
c

6.3

### 3.2 Performaning Accurate Decimal Calculations

In [6]:
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
a + b
print(a+b)
print((a+b)==Decimal('6.3'))

6.3
True


In [7]:
from decimal import Decimal
a = Decimal('1.3')
b = Decimal('1.7')
print(a/b)

0.7647058823529411764705882353


In [8]:
from decimal import localcontext
with localcontext() as ctx:
    ctx.prec = 3
    print(a/b)

0.765


In [9]:
nums = [1.23e+18, 1, -1.23e+18]
sum(nums)

0.0

In [10]:
import math
math.fsum(nums)

1.0

### 3.3. Formatting Numbers for Output

In [11]:
x = 1234.56789
format(x, '0.2f')

'1234.57'

In [12]:
format(x, '>10.1f')

'    1234.6'

In [13]:
format(x, '<10.1f')

'1234.6    '

In [14]:
format(x, '^10.1f')

'  1234.6  '

In [15]:
format(x, ',')

'1,234.56789'

In [16]:
format(x, '0,.1f')

'1,234.6'

In [17]:
format(x, 'e')

'1.234568e+03'

In [18]:
format(x, '0.2e')

'1.23e+03'

### 3.4. Working with Binary, Octal, and Hexadecimal Integers

In [19]:
x = 1234
bin(x)

'0b10011010010'

In [20]:
oct(x)

'0o2322'

In [21]:
hex(x)

'0x4d2'

In [22]:
format(x, 'b')

'10011010010'

In [23]:
format(x, 'o')

'2322'

In [24]:
format(x, 'x')

'4d2'

In [25]:
x = -1234
format(2**32+x, 'b')

'11111111111111111111101100101110'

In [26]:
format(2**32+x, 'x')

'fffffb2e'

In [27]:
int('4d2', 16)

1234

### 3.5 Packing and Unpacking Large Integers from Bytes

In [28]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
len(data)

16

In [29]:
int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [30]:
int.from_bytes(data, 'big')

94522842520747284487117727783387188

In [31]:
x = 94522842520747284487117727783387188
x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [32]:
x.to_bytes(16, 'little')

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

In [33]:
import struct
hi, lo = struct.unpack('>QQ', data)

In [34]:
(hi<<64)+lo

94522842520747284487117727783387188

In [35]:
x = 523**23

In [36]:
x

335381300113661875107536852714019056160355655333978849017944067

In [37]:
#x.to_bytes(16, 'little')

In [38]:
x.bit_length()

208

In [39]:
nbytes, rem = divmod(x.bit_length(), 8)

In [40]:
if rem:
    nbytes += 1
x.to_bytes(nbytes, 'little')

b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'

### 3.6. Performing Complex-Valued Math

In [41]:
a = complex(2, 4)
b = 3 - 5j
a

(2+4j)

In [42]:
a+b

(5-1j)

In [43]:
a.real

2.0

In [44]:
a.imag

4.0

In [45]:
a.conjugate()

(2-4j)

### 3.7. Working with Infinity and NaNs

In [46]:
a = float('inf')

In [47]:
a

inf

In [48]:
import math
math.isinf(a)

True

### 3.8. Calculating with Fractions

In [49]:
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a+b)

27/16


In [50]:
print(a*b)

35/64


### 3.9. Calculating with Large Numerical Arrays

In [51]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [52]:
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
ax * 2

array([2, 4, 6, 8])

In [53]:
ax + 10

array([11, 12, 13, 14])

In [54]:
ax + ay

array([ 6,  8, 10, 12])

In [55]:
ax*ay

array([ 5, 12, 21, 32])

In [56]:
np.sqrt(ax)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [57]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [58]:
grid = np.zeros(shape=(10000, 10000), dtype = float)

In [59]:
grid

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [60]:
np.sin(grid)

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [61]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [62]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
a[1]

array([5, 6, 7, 8])

In [64]:
a[:,1]

array([ 2,  6, 10])

In [65]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [66]:
a+[100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 107, 109, 111],
       [109, 111, 113, 115]])

### 3.10. Performing Matrix and Linear Algebra Calculations

In [67]:
import numpy as np
m = np.matrix([[1, -2, 3],[0, 4, 5],[7, 8, -9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [68]:
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [69]:
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [70]:
v = np.matrix([[2],[3], [4]])

In [71]:
v

matrix([[2],
        [3],
        [4]])

In [72]:
m*v

matrix([[ 8],
        [32],
        [ 2]])

### 3.11. Picking Things at Random

In [73]:
import random
values = [1,2, 3,4, 5,6]

In [80]:
random.choice(values)

5

In [77]:
random.sample(values, 2)

[6, 5]

In [81]:
random.shuffle(values)

In [82]:
values

[3, 5, 4, 2, 6, 1]

In [83]:
random.randint(0, 10)

9

In [84]:
random.random()

0.7435586683333658

In [85]:
random.getrandbits(200)

106488287243435770159554073582977059800685116668529457369017

### 3.12. Converting Days to Seconds, and Other Basic Time Conversions

In [86]:
from datetime import timedelta
a = timedelta(days = 2, hours = 6)
b = timedelta(hours = 4.5)
print(a)
print(b)
c = a+b
print(c.days)

2 days, 6:00:00
4:30:00
2


In [87]:
c.seconds

37800

In [88]:
c.seconds/3600

10.5

In [90]:
c.total_seconds()/3600

58.5

In [91]:
from datetime import datetime
a = datetime(2012, 9, 23)
print(a)

2012-09-23 00:00:00


In [92]:
print(a + timedelta(days = 10))

2012-10-03 00:00:00


In [93]:
now = datetime.today()

In [96]:
now
b = datetime(2012, 12, 21)

In [97]:
d = b -a

In [99]:
d.days

89

In [100]:
now = datetime.today()

In [102]:
print(now)

2018-04-02 20:50:06.708060


In [103]:
from dateutil.relativedelta import relativedelta
a = datetime(2018, 4, 2)
print(a + relativedelta(months=1))
print(a)

2018-05-02 00:00:00
2018-04-02 00:00:00


In [105]:
b = datetime(2017, 4, 2)
d = b-a
print(d)

-365 days, 0:00:00


In [106]:
d = relativedelta(a, b)
print(d)

relativedelta(years=+1)


In [109]:
d.years

1

### 3.13. Determining Last Friday’s Date

In [110]:
from datetime import datetime, timedelta
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
'Friday', 'Saturday', 'Sunday']
def get_previous_byday(dayname, start_date=None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date
get_previous_byday('Monday')

datetime.datetime(2018, 3, 26, 20, 58, 0, 553287)

### 3.14. Finding the Date Range for the Current Month

In [117]:
from datetime import datetime, date, timedelta
import calendar
def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day = 1)
    _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
    print(_)
    end_date = start_date + timedelta(days = days_in_month)
    return (start_date, end_date)
a_day = timedelta(days = 1)
first_day, last_day = get_month_range()
print(last_day)
while first_day < last_day:
    print(first_day)
    first_day += a_day

6
2018-05-01
2018-04-01
2018-04-02
2018-04-03
2018-04-04
2018-04-05
2018-04-06
2018-04-07
2018-04-08
2018-04-09
2018-04-10
2018-04-11
2018-04-12
2018-04-13
2018-04-14
2018-04-15
2018-04-16
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-21
2018-04-22
2018-04-23
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-04-28
2018-04-29
2018-04-30


In [120]:
def date_range(start, stop, step):
    while start < stop:
        yield start
        start += step
for d in date_range(datetime(2012, 2, 1), datetime(2012, 3, 2), timedelta(days = 1)):
    print(d)

2012-02-01 00:00:00
2012-02-02 00:00:00
2012-02-03 00:00:00
2012-02-04 00:00:00
2012-02-05 00:00:00
2012-02-06 00:00:00
2012-02-07 00:00:00
2012-02-08 00:00:00
2012-02-09 00:00:00
2012-02-10 00:00:00
2012-02-11 00:00:00
2012-02-12 00:00:00
2012-02-13 00:00:00
2012-02-14 00:00:00
2012-02-15 00:00:00
2012-02-16 00:00:00
2012-02-17 00:00:00
2012-02-18 00:00:00
2012-02-19 00:00:00
2012-02-20 00:00:00
2012-02-21 00:00:00
2012-02-22 00:00:00
2012-02-23 00:00:00
2012-02-24 00:00:00
2012-02-25 00:00:00
2012-02-26 00:00:00
2012-02-27 00:00:00
2012-02-28 00:00:00
2012-02-29 00:00:00
2012-03-01 00:00:00


### 3.15. Converting Strings into Datetimes

In [121]:
from datetime import datetime
text = '2012-09-20'
y = datetime.strptime(text, '%Y-%m-%d')

In [122]:
y

datetime.datetime(2012, 9, 20, 0, 0)

In [123]:
z = datetime.now()
diff = z - y

In [124]:
diff

datetime.timedelta(2020, 76768, 256472)

In [125]:
print(diff)

2020 days, 21:19:28.256472


### 3.16. Manipulating Dates Involving Time Zones

In [127]:
from datetime import datetime
from pytz import timezone
d = datetime(2012, 12, 21, 9, 30, 0)
print(d)

2012-12-21 09:30:00


In [128]:
central = timezone('US/Central')

In [129]:
loc_d = central.localize(d)
print(loc_d)

2012-12-21 09:30:00-06:00


In [130]:
bang_d = loc_d.astimezone(timezone('Asia/Tokyo'))
print(bang_d)

2012-12-22 00:30:00+09:00


In [131]:
d = datetime(2013, 3, 10, 1, 45)
loc_d = central.localize(d)
print(loc_d)

2013-03-10 01:45:00-06:00
