### 3.1 Rounding Numerical Values

In [1]:
round(1.23, 1)

1.2

In [2]:
round(1.27, 1)

1.3

In [3]:
round(-1.27, 1)

-1.3

In [4]:
a = 2.1
b = 4.2
c = a+b
c

6.300000000000001

In [6]:
c = round(c, 2)
c

6.3

### 3.2 Performaning Accurate Decimal Calculations

In [7]:
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
a + b
print(a+b)
print((a+b)==Decimal('6.3'))

6.3
True


In [8]:
from decimal import Decimal
a = Decimal('1.3')
b = Decimal('1.7')
print(a/b)

0.7647058823529411764705882353


In [11]:
from decimal import localcontext
with localcontext() as ctx:
    ctx.prec = 3
    print(a/b)

0.765


In [12]:
nums = [1.23e+18, 1, -1.23e+18]
sum(nums)

0.0

In [13]:
import math
math.fsum(nums)

1.0

### 3.3. Formatting Numbers for Output

In [14]:
x = 1234.56789
format(x, '0.2f')

'1234.57'

In [15]:
format(x, '>10.1f')

'    1234.6'

In [16]:
format(x, '<10.1f')

'1234.6    '

In [17]:
format(x, '^10.1f')

'  1234.6  '

In [18]:
format(x, ',')

'1,234.56789'

In [20]:
format(x, '0,.1f')

'1,234.6'

In [21]:
format(x, 'e')

'1.234568e+03'

In [22]:
format(x, '0.2e')

'1.23e+03'

### 3.4. Working with Binary, Octal, and Hexadecimal Integers

In [23]:
x = 1234
bin(x)

'0b10011010010'

In [24]:
oct(x)

'0o2322'

In [25]:
hex(x)

'0x4d2'

In [26]:
format(x, 'b')

'10011010010'

In [27]:
format(x, 'o')

'2322'

In [28]:
format(x, 'x')

'4d2'

In [29]:
x = -1234
format(2**32+x, 'b')

'11111111111111111111101100101110'

In [30]:
format(2**32+x, 'x')

'fffffb2e'

In [31]:
int('4d2', 16)

1234

### 3.5 Packing and Unpacking Large Integers from Bytes

In [32]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
len(data)

16

In [34]:
int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [35]:
int.from_bytes(data, 'big')

94522842520747284487117727783387188

In [37]:
x = 94522842520747284487117727783387188
x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [38]:
x.to_bytes(16, 'little')

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

In [39]:
import struct
hi, lo = struct.unpack('>QQ', data)

In [40]:
(hi<<64)+lo

94522842520747284487117727783387188

In [41]:
x = 523**23

In [42]:
x

335381300113661875107536852714019056160355655333978849017944067

In [43]:
x.to_bytes(16, 'little')

OverflowError: int too big to convert

In [44]:
x.bit_length()

208

In [45]:
nbytes, rem = divmod(x.bit_length(), 8)

In [46]:
if rem:
    nbytes += 1
x.to_bytes(nbytes, 'little')

b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'

### 3.6. Performing Complex-Valued Math

In [47]:
a = complex(2, 4)
b = 3 - 5j
a

(2+4j)

In [48]:
a+b

(5-1j)

In [49]:
a.real

2.0

In [51]:
a.imag

4.0

In [52]:
a.conjugate()

(2-4j)

### 3.7. Working with Infinity and NaNs

In [53]:
a = float('inf')

In [54]:
a

inf

In [58]:
import math
math.isinf(a)

True

### 3.8. Calculating with Fractions

In [5]:
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a+b)

27/16


In [60]:
print(a*b)

35/64


### 3.9. Calculating with Large Numerical Arrays

In [5]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
ax * 2

array([2, 4, 6, 8])

In [2]:
ax + 10

array([11, 12, 13, 14])

In [5]:
ax + ay

array([ 6,  8, 10, 12])

In [6]:
ax*ay

array([ 5, 12, 21, 32])

In [7]:
np.sqrt(ax)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [8]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [9]:
grid = np.zeros(shape=(10000, 10000), dtype = float)

In [10]:
grid

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [11]:
np.sin(grid)

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [12]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [13]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a[1]

array([5, 6, 7, 8])

In [15]:
a[:,1]

array([ 2,  6, 10])

In [16]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [17]:
a+[100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 107, 109, 111],
       [109, 111, 113, 115]])